#!/usr/bin/env bash

help()
{
    echo "a simple wrapper for rate.sx"
    echo
    echo "usage: rate.sx [ASSET]"
    exit 0
}

invalid()
{
    echo "invalid option, refer to -h"
    exit 0
}

while getopts ":h" opt; do
    case $opt in
        h) help;;
        ?) invalid;;
    esac
done

curl -s http://brl.rate.sx/$1?lang=pt-br | head -n -2 | tail -n +6
