#!/usr/bin/env bash
Protesilaos Stavrou
help()
{
    echo "a simple script to resize bspwm windows"
	echo "shamelessly stolen from Protesilaos Stavrou"
    echo
    echo "usage: resize [MOTION] [DIRECTION] [AMOUNT]"
	echo "motion: expand, retract"
	echo "directions: north, east, south, west"
	echo "amount: any intiger"
    exit 0
}

invalid()
{
    echo "invalid option, refer to -h"
    exit 0
}

while getopts ":h" opt; do
    case $opt in
        h) help;;
        ?) invalid;;
    esac
done

[ "$#" -eq 3 ] || { echo "Needs exactly three arguments."; exit 1; }

motion="$1"
direction="$2"
size="$3"

if [ "$motion" = 'expand' ]; then
	# These expand the window's given side
	case "$direction" in
		north) bspc node -z top 0 -"$size" ;;
		east) bspc node -z right "$size" 0 ;;
		south) bspc node -z bottom 0 "$size" ;;
		west) bspc node -z left -"$size" 0 ;;
	esac
else
	# These contract the window's given side
	case "$direction" in
		north) bspc node -z top 0 "$size" ;;
		east) bspc node -z right -"$size" 0 ;;
		south) bspc node -z bottom 0 -"$size" ;;
		west) bspc node -z left "$size" 0 ;;
	esac
fi
