#!/usr/bin/env bash

invalid()
{
    echo "invalid option, refer to -h"
    exit 0
}

help()
{
    echo "an attempt at create a command-line docverter wrapper"
    echo
    echo "usage convert [ORIGINAL] [TARGET]"
    exit 0
}

while getopts ":h" opt; do
    case $opt in
        h) help;;
        ?) invalid;;
    esac
done

FILE=$1
EXT="${FILE#*.}"
curl "http://c.docverter.com/convert" -F from=$EXT -F to=$2 -F "input_files[]=@$FILE" -o "resultado.$2"
