#!/usr/bin/env bash

invalid()
{
    echo "invalid option, refer to -h"
    exit 0
}

help()
{
    echo "a simple script to mute and unmute a microphone"
    echo
    echo "usage: mute"
    exit 0
}

toggle()
{
    ID=$(pactl list short | grep "easyeffects_source" | awk '{print $1;}')
    STATUS=$(pactl get-source-mute "$ID")
    if [ "$STATUS" == 'Mute: yes' ]; then
        notify-send -t 5000 "Microphone ON"
    else
        notify-send -t 5000 "Microphone OFF"
    fi
    pactl set-source-mute "$ID" toggle
}

while getopts ":h" opt; do
    case $opt in
        h) help;;
        ?) invalid;;
    esac
done

toggle
