#!/usr/bin/env bash

invalid()
{
    echo "invalid option, refer to -h"
    exit 0
}

help()
{
    echo "a simple script to curl from wttr.in"
    echo
    echo "usage: wttr.sh [LOCATION]"
    exit 0
}

while getopts ":h" opt; do
    case $opt in
        h) help;;
        ?) invalid;;
    esac
done

for i in `seq ${VARIABLE:-1}`; do
  notify-send "Timer Set"
  sleep ${VARIABLE:-2500}
  notify-send "Timer End"
done
