#!/usr/bin/env bash

invalid()
{
    echo "invalid option, refer to -h"
    exit 0
}

help()
{
    echo "a simple script to curl from wttr.in"
    echo
    echo "usage: wttr.sh [LOCATION]"
    exit 0
}

getDefaultSink() {
    defaultSink=$(pactl info | awk -F : '/Default Sink:/{print $2}')
    description=$(pactl list sinks | sed -n "/${defaultSink}/,/Description/p; /Description/q" | sed -n 's/^.*Description: \(.*\)$/\1/p')
}

getDefaultSource() {
    defaultSource=$(pactl info | awk -F : '/Default Source:/{print $2}')
    description=$(pactl list sources | sed -n "/${defaultSource}/,/Description/p; /Description/q" | sed -n 's/^.*Description: \(.*\)$/\1/p')
}

VOLUME=$(pamixer --get-volume-human)
SINK=$(getDefaultSink)
SOURCE=$(getDefaultSource)

while getopts ":h" opt; do
    case $opt in
        h) help;;
        ?) invalid;;
    esac
done

case $1 in
    "--up")
        pamixer --increase 5;;
    "--down")
        pamixer --decrease 5;;
    "--mute")
        pamixer --toggle-mute;;
    *)
        echo "${VOLUME}"
esac
